use_frameworks!

target 'ScrollSegmentsSwift_Example' do
  pod 'ScrollSegmentsSwift'

  target 'ScrollSegmentsSwift_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
